user:
 age: 123
##thymeleaf配置
spring.thymeleaf:
 mode= HTML5
 encoding= UTF-8
 content-type= text/html
 cache= false
spring.resources:
 static-locations= classpath:/layui/
 ##数据库配置
spring.datasource:
 url=jdbc:mysql://localhost:3306/test
 username=root
 password=daixilong
 driver-class-name=com.mysql.jdbc.Driver

 spring.mvc.favicon.enabled = false
 